#!/usr/bin/env bash

alias v="vim"
alias V="sudo vim"
alias jsn="python3 -m json.tool"
alias dvp="cd ~/development"
alias dox="cd ~/documents"
alias dld="cd ~/downloads"
alias pix="cd ~/pictures"
alias mvs="cd ~/movies"
alias dtf="cd ~/development/prv/dotfiles"
alias sbx="cd ~/development/prv/sandbox"
alias wlp="cd ~/pictures/wallpapers"
alias pai="cd ~/documents/personal-ai"
alias sshcf="ssh wittchen@s143.cyber-folks.pl -p 222"
