#!/usr/bin/env bash

# Creates diffs with my changes in code from the last month for PKUP report
# PKUP stands for "Podwyższone Koszty Uzyskania Przychodu" in Polish

# TODO:

# - generate report in *.doc file (consider external python script)
# - parametrize this script to make it generic

set -e

# info about developer
surname=Wittchen
name=Piotr

# info about destination directory and files
dateFormat=$(date +'%Y%m')
filePath=~/Documents/hybris/pkup/raporty/doc/"$surname"_"$name"_"$dateFormat"
fileExtension=diff

msg() {
  tput setaf 2 # green text
  echo ">>> $1"
  tput sgr 0
  sleep 1
}

setAfterDate() {
  currentMonth=$(date +%m)
  if [ $currentMonth -eq "1" ]; then
    lastMonth=12
  else
    monthsToRemove=1
    lastMonth=$(echo "$currentMonth-$monthsToRemove" | bc)
  fi

  year=$(date +%Y)
  day=20
  afterDate="$year-$lastMonth-$day"
}

saveDiff() {
  setAfterDate
  msg "saving diff for $1 commits from $afterDate"
  cd $yHYBRIS_SRC/"$1"
  gitUserName=$(git config user.name)
  mkdir -p "$filePath"
  git log --author="$gitUserName" -p --after="$afterDate" > "$filePath"/"$1"."$fileExtension"
}

removeDiffIfEmpty() {
  if [ ! -s "$filePath"/"$1"."$fileExtension" ]
  then
    msg "no changes performed in $1 -> removing empty $1.$fileExtension file"
    rm -f "$filePath"/"$1".$fileExtension
  fi
}

main() {
  projects=(backoffice platform-backoffice cockpitng backofficesearch pcm pcmbackoffice cockpit cockpit-core)

  for project in "${projects[@]}"
  do
    saveDiff $project
    removeDiffIfEmpty $project
  done
}

main "$@"
