#!/usr/bin/env bash

alias v="sudo vim"
alias s="sudo systemctl"
alias scs="cd ~/.scripts"
alias dvp="cd ~/development"
alias dox="cd ~/documents"
alias dld="cd ~/downloads"
alias pix="cd ~/pictures"
alias vid="cd ~/videos"
alias dtf="cd ~/development/prv/bash/dotfiles"
alias wlp="cd ~/pictures/wallpapers"
alias usb_in="sudo mount /dev/sdb1 /media/usb"
alias usb_out="sudo umount /media/usb"
alias sd_in="sudo mount /dev/sda1/ /media/sdcard"
alias sd_out="sudo umount /media/sdcard"
